/*
 * Add your dependencies here.
 * Supported configurations: api, implementation, compileOnly, compileOnlyApi,
 * runtimeOnlyNonPublishable, devOnlyNonPublishable, runtimeOnly, annotationProcessor,
 * shadowImplementation, testCONFIG
 *
 * For more details, see https://docs.gradle.org/8.0.1/userguide/java_library_plugin.html
 */
elytraModpackVersion {
    gtnhVersion = "2.9.0-beta-3"
    // elytra-conventions v1.1.x treats this as useCache; true lets the local manifest cache be used.
    manifestNoCache = true
    attachManifestVersionToJar = false
}

dependencies {
    implementation(gtnhDev("NotEnoughItems"))
    runtimeOnlyNonPublishable(gtnhDev("CraftTweaker")) { transitive = false }

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.hamcrest:hamcrest-core:1.3")
}

/**
 * Generate a dependency notation for GTNH projects.
 *
 * @param name       the name of the dependency in the manifest.
 * @param classifier the classifier
 * @return the generated notation
 */
String gtnhDev(String name, String classifier = "dev") {
    return elytraModpackVersion.gtnh(name, classifier)
}
